services:
  dnstt:
    build:
      context: .
      dockerfile: Dockerfile.dnstt
    image: ghcr.io/psauxwwf/t2s:dnstt
    container_name: dnstt
    restart: unless-stopped
    stop_grace_period: 20s
    volumes:
      - ./db/:/dnstt/db
    # NOT USE " "
    environment:
      - NS_QUERY=${NS_QUERY}
      - DNS_PORT=${DNS_PORT:-:53}
      - UPSTREAM=${UPSTREAM:-127.0.0.1:1080}
      - MTU=${MTU:-1400}
    network_mode: "host"
