version: "3"

dotenv: ["build.env"]

vars:
  gobin: go
  ldflags: "-extldflags '-static' -w -s -buildid="
  gcflags: "all=-trimpath={{.PWD}} -dwarf=false -l"
  asmflags: "all=-trimpath={{.PWD}}"
  bin: "{{.PWD}}/bin"
  app: "t2s"
  app_bin: "{{.bin}}/{{.app}}"
  release_linux_archive: "{{.bin}}/{{.app}}_linux_amd64.tar.gz"

env:
  CGO_ENABLED: 0
  GOARCH: amd64
  GOOS: linux

tasks:
  setup:
    desc: set up the environment
    internal: true
    silent: true
    cmds:
      - mkdir -p {{.bin}}

  build:
    desc: common build
    deps:
      - build:linux

  build:linux:
    desc: build for linux amd64
    deps:
      - setup
    silent: true
    cmds:
      - >
        {{.gobin}} build
        -tags netgo
        -ldflags="{{.ldflags}}" 
        -trimpath 
        -gcflags="{{.gcflags}}" 
        -asmflags="{{.asmflags}}" 
        -o {{.app_bin}} cmd/{{.app}}/main.go
      - strip {{.app_bin}}
      - objcopy --strip-unneeded {{.app_bin}}

  release:
    desc: build and publish github release
    deps:
      - build
    silent: false
    cmds:
      - tar -czf {{.release_linux_archive}} -C {{.bin}} {{.app}}
      - |
        TAG=$(date +%m.%d.%H)
        gh release create "$TAG" {{.release_linux_archive}}

  build:docker:dnstt:
    desc: build docker dnstt server image
    cmds:
      - docker compose -f docker-compose.dnstt.yaml build

  docker:dnstt:up:
    desc: build docker dnstt server and up image
    cmds:
      - docker compose -f docker-compose.dnstt.yaml up --build --force-recreate

  docker:dnstt:push:
    desc: push docker dnstt server image
    deps:
      - build:docker:dnstt
    cmds:
      - docker compose -f docker-compose.dnstt.yaml push
