package dns

import (
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"t2s/pkg/fs"
	"t2s/pkg/shell"
)

var (
	resolvconf = `
# Generated by t2s.
# Stop t2s for return default config.
nameserver %s
`
	respath        = filepath.Join("/", "etc", "resolv.conf")
	respathsystemd = filepath.Join("/", "run", "systemd", "resolve", "stub-resolv.conf")
	reInterfaces   = regexp.MustCompile(`\((\w+)\)`)
)

type manager struct {
	listen            string
	search            []string
	render, resolvect bool
	link              string
	currentconf       []byte
}

func Manager(
	_listen string,
	_search []string,
	_render, _resolvectl bool,
) (*manager, error) {
	_manager := &manager{
		listen:    _listen,
		search:    normalizeSearch(_search),
		render:    _render,
		resolvect: _resolvectl,
	}
	if _manager.render {
		currentconf, err := fs.ReadFile(respath)
		if err != nil {
			return nil, fmt.Errorf("failed to read: %w", err)
		}
		_manager.currentconf = currentconf
		link, err := fs.CheckSymlink(respath)
		if err != nil {
			slog.Warn("check symlink", "error", err)
		}
		_manager.link = link
	}
	return _manager, nil
}

func (m *manager) Set() error {
	return errors.Join(
		func() error {
			if m.render {
				if m.link != "" {
					if err := os.RemoveAll(respath); err != nil {
						return fmt.Errorf("failed to unlink %s: %w", respath, err)
					}
				}
				if err := render(respath, m.listen, m.search); err != nil {
					return fmt.Errorf("resolvconf error: %w", err)
				}
			}
			return nil
		}(),
		func() error {
			if m.resolvect {
				for _, i := range m.getInterfaces() {
					if _, err := shell.New("resolvectl", "dns", i, m.listen).Run(); err != nil {
						return fmt.Errorf("failed to set dns %s for %s: %w", m.listen, i, err)
					}
					if len(m.search) > 0 {
						args := append([]string{"domain", i}, m.search...)
						if _, err := shell.New("resolvectl", args...).Run(); err != nil {
							return fmt.Errorf("failed to set search domains %s for %s: %w", strings.Join(m.search, " "), i, err)
						}
					}
				}
			}
			return nil
		}(),
	)
}

func (m *manager) Revert() error {
	return errors.Join(
		func() error {
			if m.render {
				if m.link != "" {
					if err := os.RemoveAll(respath); err != nil {
						return fmt.Errorf("failed to unlink %s: %w", respath, err)
					}
				}
				if err := os.Symlink(m.link, respath); err != nil {
					return fmt.Errorf("error creating symlink: %v", err)
				}
				if err := fs.WriteFile(respath, m.currentconf); err != nil {
					return fmt.Errorf("resolvconf error: %w", err)
				}
			}
			return nil
		}(),
		func() error {
			if m.resolvect {
				for _, i := range m.getInterfaces() {
					if _, err := shell.New("resolvectl", "revert", i).Run(); err != nil {
						return fmt.Errorf("failed to revert dns for %s: %w", i, err)
					}
				}
				if _, err := shell.New("systemctl", "--no-block", "restart", "systemd-resolved").Run(); err != nil {
					return fmt.Errorf("failed to restart dns: %w", err)
				}
			}
			return nil
		}(),
	)
}

func (m *manager) Repair() error {
	return errors.Join(
		os.RemoveAll(respath),
		os.Symlink(respathsystemd, respath),
		func() error {
			for _, i := range m.getInterfaces() {
				if _, err := shell.New("resolvectl", "revert", i).Run(); err != nil {
					return fmt.Errorf("failed to revert dns for %s: %w", i, err)
				}
			}
			return nil
		}(),
		func() error {
			if _, err := shell.New("systemctl", "restart", "systemd-resolved").Run(); err != nil {
				return err
			}
			return nil
		}(),
	)
}

func render(path, listen string, search []string) error {
	data := fmt.Appendf(nil, resolvconf, listen)
	if len(search) > 0 {
		data = fmt.Appendf(data, "search %s\n", strings.Join(search, " "))
	}
	if err := fs.WriteFile(path, data); err != nil {
		return fmt.Errorf("failed to render: %w", err)
	}
	return nil
}

func normalizeSearch(search []string) []string {
	var normalized []string
	for _, domain := range search {
		if domain = strings.TrimSpace(domain); domain != "" {
			normalized = append(normalized, domain)
		}
	}
	return normalized
}

func (m *manager) getInterfaces() (interfaces []string) {
	out, err := shell.New("resolvectl", "dns").Run()
	if err != nil {
		slog.Warn("failed to get interfaces", "error", err)
		return
	}
	for _, match := range reInterfaces.FindAllStringSubmatch(out, -1) {
		interfaces = append(interfaces, match[1])
	}
	return
}
